name: sample pwd
on:
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: sample pwd
      run: |
        MY_VAR=$(pwd)
        echo "My variable is $MY_VAR"
        MY_VAR=${MY_VAR%/*}
        echo "My variable is $MY_VAR"
        MY_VAR=${MY_VAR%/*/*}/raj
        echo "My variable is $MY_VAR"