name: sample pwd
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      run: |
        MY_VAR=$(pwd)
        echo "My variable is $MY_VAR"
        MY_VAR=${MY_VAR%/*}/raj
        echo "My variable is $MY_VAR"